@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Igor Galindo",
    "email": "igor@email.com",
    "password": "123456"
}

###

